[package]
name = "spc700-rs"
version = "0.1.0"
authors = ["soya <ohnishi.soya@arc.cs.okayama-u.ac.jp>"]
edition = "2021"

[profile.release]
debug = 1

[dependencies]
spc = "0.1.1"
cpal = "0.14"
hound = "3.5"
clap = { version = "4.0", features = ["derive"] }