[package]
name = "spc700-core"
version = "0.1.0"
authors = ["SoyaOhnishi"]
edition = "2021"

[profile.release]
debug = 1

[dependencies]
spc = "0.1.1"
cpal = "0.14"
hound = "3.5"
clap = { version = "4.0", features = ["derive"] }
array-macro = "2.1"
typenum = "1.15"
log = "0.4"
env_logger = "0.10"